/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lucene_cyborg_jni_IndexSearcherProxy */

#ifndef _Included_lucene_cyborg_jni_IndexSearcherProxy
#define _Included_lucene_cyborg_jni_IndexSearcherProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lucene_cyborg_jni_IndexSearcherProxy
 * Method:    search
 * Signature: (JLlucene/cyborg/jni/query/QueryData;Llucene/cyborg/jni/collector/CollectorManagerData;)V
 */
JNIEXPORT void JNICALL Java_lucene_cyborg_jni_IndexSearcherProxy_search
    (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     lucene_cyborg_jni_IndexSearcherProxy
 * Method:    aggregate
 * Signature: (JLlucene/cyborg/jni/query/QueryData;Llucene/cyborg/jni/aggregator/AggregatorManagerData;)V
 */
JNIEXPORT void JNICALL Java_lucene_cyborg_jni_IndexSearcherProxy_aggregate
    (JNIEnv *, jobject, jlong, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
