/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lucene_cyborg_jni_StaticMMapDirectoryReader */

#ifndef _Included_lucene_cyborg_jni_StaticMMapDirectoryReader
#define _Included_lucene_cyborg_jni_StaticMMapDirectoryReader
#ifdef __cplusplus
extern "C" {
#endif
#undef lucene_cyborg_jni_StaticMMapDirectoryReader_NULL_POINTER
#define lucene_cyborg_jni_StaticMMapDirectoryReader_NULL_POINTER 0i64
/*
 * Class:     lucene_cyborg_jni_StaticMMapDirectoryReader
 * Method:    openMmapDirectoryReader
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_lucene_cyborg_jni_StaticMMapDirectoryReader_openMmapDirectoryReader
    (JNIEnv *, jclass, jstring);

/*
 * Class:     lucene_cyborg_jni_StaticMMapDirectoryReader
 * Method:    closeMmapDirectoryReader
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_lucene_cyborg_jni_StaticMMapDirectoryReader_closeMmapDirectoryReader
    (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
